export const Repositories = {
    USER_REPOSITORY: 'USER_REPOSITORY',
    USER_PASSWORD_REPOSITORY: 'USER_PASSWORD_REPOSITORY',
    TENANT_REPOSITORY: 'TENANT_REPOSITORY',
    ADDRESS_REPOSITORY: 'ADDRESS_REPOSITORY',
    LICENSE_REPOSITORY: 'LICENSE_REPOSITORY',
}